name: "flight_booking"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    volumes:
      - mssql:/var/opt/mssql
    platform: "linux/amd64"
    expose:
      - "1433"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Mysecret_password21
  web:
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlserver://mssql:1433;database=flight_booking;integratedSecurity=true;username=sa;password=Mysecret_password21;trustServerCertificate=true;
    depends_on:
      - "mssql"
    command: ["./wait-for-it.sh", "mssql:1433", "--", "node", "dist/main.js"]

volumes:
  mssql:
